# Generated by Django 5.2 on 2025-04-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.RunSQL("""
        
            INSERT INTO store_collection (title)
            VALUES ('collection1')
        """, """ 
            DELETE FROM store_collection
            WHERE title='collection1'
        """
                          )
    ]
