# Generated by Django 5.2 on 2025-04-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_orderitem_product_alter_product_collections_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revies',
            new_name='Review',
        ),
    ]
